default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pokelist_development

test:
  <<: *default
  database: pokelist_test

production:
  <<: *default
  database: pokelist_production
  username: pokelist
  password: <%= ENV['POKELIST_DATABASE_PASSWORD'] %>
